import { renderPhoto } from "@/lib/media/homepage-photo";

/**
 * One editorial photograph, driven entirely by the acquisition manifest.
 *
 * Renders a plain <img> rather than next/image on purpose: the Cloudflare
 * adapter runs with `images: { unoptimized: true }`, so next/image would add a
 * wrapper and a runtime cost while doing no resizing. Every width in the
 * srcSet is pre-generated by scripts/acquire-homepage-photography.mjs.
 *
 * width/height are always emitted so the browser reserves the correct box
 * before the bytes arrive -- without them a full-bleed hero shifts the entire
 * page as it loads.
 */
export default function EditorialImage({
  slot,
  sizes,
  priority = false,
  className = "",
  alt,
}: {
  slot: string;
  sizes: string;
  /** Only the hero should be priority: everything else is below the fold. */
  priority?: boolean;
  className?: string;
  alt: string;
}) {
  const photo = renderPhoto(slot);
  if (!photo) return null;

  const img = (
    <img
      src={photo.src}
      srcSet={photo.srcSet}
      sizes={sizes}
      width={photo.width}
      height={photo.height}
      alt={alt}
      loading={priority ? "eager" : "lazy"}
      decoding={priority ? "sync" : "async"}
      fetchPriority={priority ? "high" : "auto"}
      className={className}
    />
  );

  /*
   * A <picture> only where AVIF renditions exist. AVIF is markedly better on
   * dense, high-frequency subjects -- the Workhorse frame's bare branches cost
   * 473KB as WebP and 177KB as AVIF at the same width -- but it is not worth
   * the encode on smooth skies, so most slots ship WebP alone and fall
   * straight through to the <img>.
   */
  if (!photo.avifSrcSet) return img;

  return (
    <picture>
      <source type="image/avif" srcSet={photo.avifSrcSet} sizes={sizes} />
      {img}
    </picture>
  );
}
