/* =========================================================
   AFTERMARKET TEST INVENTORY (30 PRODUCTS)
   ---------------------------------------------------------
   Seed data for /aftermarket marketplace validation only.
   Does not affect engine, turbocharger, or other categories.
========================================================= */

import type { Product } from "./types";

const IMG = {
  engine: "/engines/engine-1.jpg",
  turbo: "/turbochargers/turbo-1.jpg",
  brakes: "/home/pexels-garvin-st-villier-719266-14277598.jpg",
  suspension: "/home/pexels-matreding-9381019.jpg",
  electronics: "/home/pexels-stephanlouis-7012890.jpg",
  lighting: "/home/pexels-juan-montes-92812630-11456554.jpg",
  body: "/home/pexels-artempodrez-8986047.jpg",
};

export const aftermarketProducts: Product[] = [
  {
    id: 3,
    name: "Toyota OEM 130A Alternator",
    category: "aftermarket",
    brand: "toyota",
    price: 189,
    stock: true,
    stockQty: 14,
    condition: "New",
    location: "USA Warehouse",
    thumbnail: IMG.engine,
    createdAt: 1704067200000,
    description:
      "Toyota OEM-spec alternator for Camry, Corolla, and RAV4 platforms. Bench-tested charging output.",
  },
  {
    id: 4,
    name: "Toyota Remanufactured Starter Motor",
    category: "aftermarket",
    brand: "toyota",
    price: 128,
    stock: true,
    stockQty: 9,
    condition: "Remanufactured",
    location: "USA Warehouse",
    thumbnail: IMG.engine,
    createdAt: 1706745600000,
    description:
      "Remanufactured Toyota starter with new solenoid contacts and armature inspection.",
  },
  {
    id: 5,
    name: "Honda 90A Alternator Assembly",
    category: "aftermarket",
    brand: "honda",
    price: 95,
    stock: true,
    stockQty: 18,
    condition: "Used",
    location: "USA Warehouse",
    thumbnail: IMG.engine,
    createdAt: 1709251200000,
    description:
      "Used Honda alternator pulled from low-mile donor. Verified charging at 13.8V+.",
  },
  {
    id: 6,
    name: "Honda Civic Starter Motor",
    category: "aftermarket",
    brand: "honda",
    price: 110,
    stock: true,
    stockQty: 11,
    condition: "Remanufactured",
    location: "USA Warehouse",
    thumbnail: IMG.engine,
    createdAt: 1711929600000,
    description:
      "Remanufactured starter for K-series and R18 platforms with new drive gear.",
  },
  {
    id: 7,
    name: "BMW N55 180A Alternator",
    category: "aftermarket",
    brand: "bmw",
    price: 245,
    stock: true,
    stockQty: 6,
    condition: "Refurbished",
    location: "USA Warehouse",
    thumbnail: IMG.engine,
    createdAt: 1714521600000,
    description:
      "Refurbished BMW N55 alternator for F30/F32 applications. Load-tested to OEM spec.",
  },
  {
    id: 8,
    name: "BMW E90 Starter Motor",
    category: "aftermarket",
    brand: "bmw",
    price: 165,
    stock: true,
    stockQty: 4,
    condition: "Used",
    location: "USA Warehouse",
    thumbnail: IMG.engine,
    createdAt: 1717200000000,
    description:
      "Used BMW starter from N52-powered E90. Compression test verified before pull.",
  },
  {
    id: 9,
    name: "Mercedes-Benz M276 Alternator",
    category: "aftermarket",
    brand: "mercedes-benz",
    price: 275,
    stock: true,
    stockQty: 7,
    condition: "New",
    location: "USA Warehouse",
    thumbnail: IMG.engine,
    createdAt: 1719792000000,
    description:
      "New Mercedes-Benz M276 alternator for W204/W212 chassis. OEM connector and pulley.",
  },
  {
    id: 10,
    name: "Mercedes-Benz OM642 Turbocharger",
    category: "aftermarket",
    brand: "mercedes-benz",
    price: 890,
    stock: true,
    stockQty: 3,
    condition: "Refurbished",
    location: "UK Warehouse",
    thumbnail: IMG.turbo,
    createdAt: 1722470400000,
    description:
      "Refurbished OM642 VGT turbo with new actuator and balanced CHRA assembly.",
  },
  {
    id: 11,
    name: "Audi B8 LED Headlight Pair",
    category: "aftermarket",
    brand: "audi",
    price: 320,
    stock: true,
    stockQty: 5,
    condition: "Used",
    location: "USA Warehouse",
    thumbnail: IMG.lighting,
    createdAt: 1725148800000,
    description:
      "Used Audi B8 LED headlight set with clear lenses. No moisture intrusion.",
  },
  {
    id: 12,
    name: "Audi A4 Tail Light Assembly",
    category: "aftermarket",
    brand: "audi",
    price: 185,
    stock: true,
    stockQty: 8,
    condition: "Refurbished",
    location: "USA Warehouse",
    thumbnail: IMG.lighting,
    createdAt: 1727740800000,
    description:
      "Refurbished inner and outer tail light housings for B8 A4 sedan.",
  },
  {
    id: 13,
    name: "Ford Mustang GT Brake Caliper",
    category: "aftermarket",
    brand: "ford",
    price: 145,
    stock: true,
    stockQty: 10,
    condition: "Remanufactured",
    location: "USA Warehouse",
    thumbnail: IMG.brakes,
    createdAt: 1730419200000,
    description:
      "Remanufactured front brake caliper for S550 Mustang GT with new seals and pistons.",
  },
  {
    id: 14,
    name: "Ford F-150 Front Strut Assembly",
    category: "aftermarket",
    brand: "ford",
    price: 78,
    stock: true,
    stockQty: 16,
    condition: "Used",
    location: "USA Warehouse",
    thumbnail: IMG.suspension,
    createdAt: 1733011200000,
    description:
      "Used front strut assembly from 2018 F-150. No leaks, smooth rebound.",
  },
  {
    id: 15,
    name: "Chevrolet Silverado Radiator",
    category: "aftermarket",
    brand: "chevrolet",
    price: 210,
    stock: true,
    stockQty: 12,
    condition: "New",
    location: "USA Warehouse",
    thumbnail: IMG.engine,
    createdAt: 1735689600000,
    description:
      "New aluminum radiator for GMT K2XX Silverado/Sierra. Direct-fit OEM replacement.",
  },
  {
    id: 16,
    name: "Chevrolet LS3 ECU Module",
    category: "aftermarket",
    brand: "chevrolet",
    price: 425,
    stock: true,
    stockQty: 2,
    condition: "Refurbished",
    location: "USA Warehouse",
    thumbnail: IMG.electronics,
    createdAt: 1738368000000,
    description:
      "Refurbished LS3 engine control module flashed and communication-tested.",
  },
  {
    id: 17,
    name: "Nissan 350Z Alternator",
    category: "aftermarket",
    brand: "nissan",
    price: 88,
    stock: true,
    stockQty: 13,
    condition: "Used",
    location: "USA Warehouse",
    thumbnail: IMG.engine,
    createdAt: 1740787200000,
    description:
      "Used VQ35DE alternator from low-mile 350Z. Charging output verified.",
  },
  {
    id: 18,
    name: "Nissan GT-R Turbocharger Cartridge",
    category: "aftermarket",
    brand: "nissan",
    price: 650,
    stock: true,
    stockQty: 2,
    condition: "Refurbished",
    location: "UK Warehouse",
    thumbnail: IMG.turbo,
    createdAt: 1743465600000,
    description:
      "Refurbished R35 GT-R turbo cartridge with balanced turbine wheel.",
  },
  {
    id: 19,
    name: "Lexus IS250 Door Panel (RH Front)",
    category: "aftermarket",
    brand: "lexus",
    price: 340,
    stock: true,
    stockQty: 3,
    condition: "Used",
    location: "USA Warehouse",
    thumbnail: IMG.body,
    createdAt: 1746057600000,
    description:
      "Used passenger front door panel from Lexus IS250. No cracks or sun fade.",
  },
  {
    id: 20,
    name: "Lexus RX350 Side Mirror",
    category: "aftermarket",
    brand: "lexus",
    price: 125,
    stock: true,
    stockQty: 9,
    condition: "Refurbished",
    location: "USA Warehouse",
    thumbnail: IMG.body,
    createdAt: 1748736000000,
    description:
      "Refurbished power-folding side mirror with working turn signal and heat.",
  },
  {
    id: 21,
    name: "Jeep Wrangler Cold Air Intake",
    category: "aftermarket",
    brand: "jeep",
    price: 165,
    stock: true,
    stockQty: 15,
    condition: "New",
    location: "USA Warehouse",
    thumbnail: IMG.turbo,
    createdAt: 1751328000000,
    description:
      "New cold air intake kit for JK/JL Wrangler 3.6L. Includes heat shield and filter.",
  },
  {
    id: 22,
    name: "Jeep Grand Cherokee Brake Caliper",
    category: "aftermarket",
    brand: "jeep",
    price: 95,
    stock: true,
    stockQty: 7,
    condition: "Used",
    location: "USA Warehouse",
    thumbnail: IMG.brakes,
    createdAt: 1754006400000,
    description:
      "Used rear brake caliper from WK2 Grand Cherokee. Piston moves freely.",
  },
  {
    id: 23,
    name: "Toyota Tacoma LED Headlights",
    category: "aftermarket",
    brand: "toyota",
    price: 220,
    stock: true,
    stockQty: 6,
    condition: "Refurbished",
    location: "USA Warehouse",
    thumbnail: IMG.lighting,
    createdAt: 1756684800000,
    description:
      "Refurbished LED headlight pair for third-gen Tacoma with upgraded DRL board.",
  },
  {
    id: 24,
    name: "Honda Accord Radiator",
    category: "aftermarket",
    brand: "honda",
    price: 72,
    stock: true,
    stockQty: 20,
    condition: "Used",
    location: "USA Warehouse",
    thumbnail: IMG.engine,
    createdAt: 1759276800000,
    description:
      "Used radiator from 2016 Accord 2.4L. Pressure tested, no core damage.",
  },
  {
    id: 25,
    name: "BMW F30 Front Control Arm",
    category: "aftermarket",
    brand: "bmw",
    price: 198,
    stock: true,
    stockQty: 8,
    condition: "Refurbished",
    location: "USA Warehouse",
    thumbnail: IMG.suspension,
    createdAt: 1761955200000,
    description:
      "Refurbished front lower control arm with new bushings and ball joint.",
  },
  {
    id: 26,
    name: "Mercedes-Benz W204 Starter",
    category: "aftermarket",
    brand: "mercedes-benz",
    price: 155,
    stock: true,
    stockQty: 5,
    condition: "Used",
    location: "USA Warehouse",
    thumbnail: IMG.engine,
    createdAt: 1764547200000,
    description:
      "Used starter motor from C250 W204. Spin test passed, clean commutator.",
  },
  {
    id: 27,
    name: "Audi Q5 Power Mirror",
    category: "aftermarket",
    brand: "audi",
    price: 142,
    stock: true,
    stockQty: 10,
    condition: "New",
    location: "USA Warehouse",
    thumbnail: IMG.body,
    createdAt: 1767225600000,
    description:
      "New driver-side power mirror for Q5 8R chassis with blind-spot indicator.",
  },
  {
    id: 28,
    name: "Ford EcoBoost Turbocharger",
    category: "aftermarket",
    brand: "ford",
    price: 720,
    stock: true,
    stockQty: 4,
    condition: "Refurbished",
    location: "USA Warehouse",
    thumbnail: IMG.turbo,
    createdAt: 1769904000000,
    description:
      "Refurbished 2.3L EcoBoost turbo for Mustang and Focus RS platforms.",
  },
  {
    id: 29,
    name: "Chevrolet Camaro Tail Lights",
    category: "aftermarket",
    brand: "chevrolet",
    price: 68,
    stock: true,
    stockQty: 14,
    condition: "Used",
    location: "USA Warehouse",
    thumbnail: IMG.lighting,
    createdAt: 1772323200000,
    description:
      "Used tail light set from fifth-gen Camaro. Lenses clear, no broken tabs.",
  },
  {
    id: 30,
    name: "Nissan Altima ECU",
    category: "aftermarket",
    brand: "nissan",
    price: 380,
    stock: true,
    stockQty: 3,
    condition: "Refurbished",
    location: "USA Warehouse",
    thumbnail: IMG.electronics,
    createdAt: 1775001600000,
    description:
      "Refurbished engine control unit for QR25DE Altima. VIN-matched programming available.",
  },
  {
    id: 31,
    name: "Lexus GS350 Air Intake System",
    category: "aftermarket",
    brand: "lexus",
    price: 189,
    stock: true,
    stockQty: 11,
    condition: "New",
    location: "USA Warehouse",
    thumbnail: IMG.turbo,
    createdAt: 1777593600000,
    description:
      "New performance intake for GS350 3.5L V6 with reusable filter and velocity stack.",
  },
  {
    id: 32,
    name: "Jeep Cherokee Door Panel (LH Rear)",
    category: "aftermarket",
    brand: "jeep",
    price: 290,
    stock: false,
    stockQty: 0,
    condition: "Used",
    location: "USA Warehouse",
    thumbnail: IMG.body,
    createdAt: 1780272000000,
    description:
      "Used rear left door panel from KL Cherokee. Minor scuff, structurally sound.",
  },
];
