/* =========================================================
   DRIVORAPARTS — BRANDS (SINGLE SOURCE OF TRUTH)
   ---------------------------------------------------------
   Brands are grouped by category slug. Each brand `slug` is
   the kebab-case form of its `name` so it resolves cleanly
   in /catalog/[category]/[brand] routes.
========================================================= */

import type { Brand } from "./types";

export const brands: Brand[] = [
  // Engine
  { slug: "bmw", name: "BMW", category: "engine" },
  { slug: "toyota", name: "Toyota", category: "engine" },
  { slug: "nissan", name: "Nissan", category: "engine" },
  { slug: "honda", name: "Honda", category: "engine" },
  { slug: "mazda", name: "Mazda", category: "engine" },
  { slug: "chevrolet", name: "Chevrolet", category: "engine" },
  { slug: "ford", name: "Ford", category: "engine" },
  { slug: "dodge", name: "Dodge", category: "engine" },
  { slug: "aeromotive", name: "Aeromotive", category: "engine" },
  { slug: "holley", name: "Holley", category: "engine" },
  { slug: "garrett", name: "Garrett", category: "engine" },
  { slug: "borgwarner", name: "BorgWarner", category: "engine" },
  { slug: "precision", name: "Precision", category: "engine" },
  { slug: "hks", name: "HKS", category: "engine" },
  { slug: "turbosmart", name: "Turbosmart", category: "engine" },
  { slug: "forge-motorsport", name: "Forge Motorsport", category: "engine" },

  // Turbocharger
  { slug: "garrett", name: "Garrett", category: "turbocharger" },
  { slug: "borgwarner", name: "BorgWarner", category: "turbocharger" },
  { slug: "precision", name: "Precision", category: "turbocharger" },
  { slug: "audi", name: "Audi", category: "turbocharger" },
  { slug: "bmw", name: "BMW", category: "turbocharger" },
  { slug: "universal", name: "Universal", category: "turbocharger" },

  // Transmission
  { slug: "zf", name: "ZF", category: "transmission" },
  { slug: "gm", name: "GM", category: "transmission" },
  { slug: "ford", name: "Ford", category: "transmission" },
  { slug: "tremec", name: "Tremec", category: "transmission" },
  { slug: "nissan", name: "Nissan", category: "transmission" },
  { slug: "toyota", name: "Toyota", category: "transmission" },
  { slug: "mercedes-benz", name: "Mercedes-Benz", category: "transmission" },
  { slug: "audi", name: "Audi", category: "transmission" },
  { slug: "bmw", name: "BMW", category: "transmission" },
  { slug: "universal", name: "Universal", category: "transmission" },
  { slug: "getrag", name: "Getrag", category: "transmission" },
  { slug: "aisin", name: "Aisin", category: "transmission" },
  { slug: "allison", name: "Allison", category: "transmission" },
  { slug: "nismo", name: "Nismo", category: "transmission" },
  { slug: "ford-performance", name: "Ford Performance", category: "transmission" },
  { slug: "chevrolet-performance", name: "Chevrolet Performance", category: "transmission" },
  { slug: "atsg", name: "ATSG", category: "transmission" },
  { slug: "sonnax", name: "Sonnax", category: "transmission" },
  { slug: "transgo", name: "TransGo", category: "transmission" },
  { slug: "xtreme-clutch", name: "Xtreme Clutch", category: "transmission" },
  { slug: "exedy", name: "Exedy", category: "transmission" },
  { slug: "act", name: "ACT", category: "transmission" },
  { slug: "south-bend", name: "South Bend Clutch", category: "transmission" },
  { slug: "centerforce", name: "Centerforce", category: "transmission" },

  // Bumpers
  { slug: "arb", name: "ARB", category: "bumper" },
  { slug: "tjm", name: "TJM", category: "bumper" },
  { slug: "ironman-4x4", name: "Ironman 4x4", category: "bumper" },
  { slug: "ecb", name: "ECB", category: "bumper" },
  { slug: "afn", name: "AFN", category: "bumper" },
  { slug: "add-offroad", name: "ADD Offroad", category: "bumper" },
  { slug: "dv8-offroad", name: "DV8 Offroad", category: "bumper" },
  { slug: "fab-fours", name: "Fab Fours", category: "bumper" },
  { slug: "rough-country", name: "Rough Country", category: "bumper" },
  { slug: "duraflex", name: "Duraflex", category: "bumper" },
  { slug: "liberty-walk", name: "Liberty Walk", category: "bumper" },
  { slug: "rocket-bunny", name: "Rocket Bunny", category: "bumper" },
  { slug: "ford", name: "Ford", category: "bumper" },
  { slug: "nissan", name: "Nissan", category: "bumper" },
  { slug: "roo-riders", name: "Roo Riders", category: "bumper" },

  // Canopies
  { slug: "arb", name: "ARB", category: "canopy" },
  { slug: "rsi-smartcap", name: "RSI SmartCap", category: "canopy" },
  { slug: "alu-cab", name: "Alu-Cab", category: "canopy" },
  { slug: "aeroklas", name: "Aeroklas", category: "canopy" },
  { slug: "egr", name: "EGR", category: "canopy" },
  { slug: "carryboy", name: "Carryboy", category: "canopy" },
  { slug: "flexiglass", name: "Flexiglass", category: "canopy" },
  { slug: "norweld", name: "Norweld", category: "canopy" },
  { slug: "boss-aluminium", name: "Boss Aluminium", category: "canopy" },
  { slug: "mrt", name: "MRT", category: "canopy" },
  { slug: "hsp", name: "HSP", category: "canopy" },
  { slug: "razorback", name: "Razorback", category: "canopy" },
  { slug: "tjm", name: "TJM", category: "canopy" },
  { slug: "mountain-top", name: "Mountain Top", category: "canopy" },
  { slug: "truck-covers-usa", name: "Truck Covers USA", category: "canopy" },
  { slug: "leer", name: "Leer", category: "canopy" },
  { slug: "snugtop", name: "SnugTop", category: "canopy" },
  { slug: "are-covers", name: "A.R.E.", category: "canopy" },
  { slug: "century", name: "Century", category: "canopy" },
  { slug: "jason", name: "Jason", category: "canopy" },
  { slug: "ranch", name: "Ranch", category: "canopy" },
  { slug: "front-runner", name: "Front Runner", category: "canopy" },

  // Brakes
  { slug: "brembo-gt-kits", name: "Brembo GT Kits", category: "brakes" },
  { slug: "brembo-oem", name: "Brembo OEM", category: "brakes" },
  { slug: "wilwood-big-brake-kits", name: "Wilwood Big Brake Kits", category: "brakes" },
  { slug: "ebc-rotors-pads", name: "EBC Rotors & Pads", category: "brakes" },
  { slug: "ate-oem-kits", name: "ATE OEM Kits", category: "brakes" },
  { slug: "ceika", name: "CEIKA", category: "brakes" },

  // Suspension
  { slug: "old-man-emu", name: "Old Man Emu (OME / ARB)", category: "suspension" },
  { slug: "dobinsons", name: "Dobinsons", category: "suspension" },
  { slug: "bilstein", name: "Bilstein", category: "suspension" },
  { slug: "fox-racing-shox", name: "Fox Racing Shox", category: "suspension" },
  { slug: "king-shocks", name: "King Shocks", category: "suspension" },
  { slug: "ironman-4x4", name: "Ironman 4x4", category: "suspension" },
  { slug: "tough-dog", name: "Tough Dog", category: "suspension" },

  // Electronics
  { slug: "aem", name: "AEM", category: "electronics" },
  { slug: "aeromotive", name: "Aeromotive", category: "electronics" },
  { slug: "holley", name: "Holley", category: "electronics" },
  { slug: "cobb", name: "COBB Tuning", category: "electronics" },
  { slug: "haltech", name: "Haltech", category: "electronics" },
  { slug: "hp-tuners", name: "HP Tuners", category: "electronics" },
  { slug: "msd", name: "MSD", category: "electronics" },
  { slug: "carlinkit", name: "CarlinKit", category: "electronics" },
  { slug: "ottocast", name: "Ottocast", category: "electronics" },
  { slug: "volkswagen", name: "Volkswagen", category: "electronics" },
  { slug: "universal", name: "Universal", category: "electronics" },

  // Lighting
  { slug: "alpharex", name: "AlphaRex", category: "lighting" },
  { slug: "baja-designs", name: "Baja Designs", category: "lighting" },
  { slug: "diode-dynamics", name: "Diode Dynamics", category: "lighting" },
  { slug: "govee", name: "Govee", category: "lighting" },
  { slug: "morimoto", name: "Morimoto", category: "lighting" },
  { slug: "opt7", name: "OPT7", category: "lighting" },
  { slug: "oracle", name: "Oracle Lighting", category: "lighting" },
  { slug: "osram", name: "Osram", category: "lighting" },
  { slug: "philips", name: "Philips", category: "lighting" },
  { slug: "rigid-industries", name: "Rigid Industries", category: "lighting" },
  { slug: "xk-glow", name: "XK Glow", category: "lighting" },
  { slug: "anzo", name: "Anzo USA", category: "lighting" },
  { slug: "spyder", name: "Spyder Auto", category: "lighting" },
  { slug: "vland", name: "VLAND", category: "lighting" },
  { slug: "toyota", name: "Toyota Genuine", category: "lighting" },
  { slug: "ford", name: "Ford Genuine", category: "lighting" },
  { slug: "nissan", name: "Nissan Genuine", category: "lighting" },
  { slug: "isuzu", name: "Isuzu Genuine", category: "lighting" },
  { slug: "porsche", name: "Porsche", category: "lighting" },
  { slug: "mars-performance", name: "Mars Performance", category: "lighting" },
  { slug: "universal", name: "Universal", category: "lighting" },

  // Body Parts
  { slug: "bmw", name: "BMW", category: "body-parts" },
  { slug: "chevrolet", name: "Chevrolet", category: "body-parts" },
  { slug: "dodge", name: "Dodge", category: "body-parts" },
  { slug: "ford", name: "Ford", category: "body-parts" },
  { slug: "gmc", name: "GMC", category: "body-parts" },
  { slug: "honda", name: "Honda", category: "body-parts" },
  { slug: "nissan", name: "Nissan", category: "body-parts" },
  { slug: "subaru", name: "Subaru", category: "body-parts" },
  { slug: "toyota", name: "Toyota", category: "body-parts" },
  { slug: "volkswagen", name: "Volkswagen", category: "body-parts" },
  { slug: "universal", name: "Universal", category: "body-parts" },

  // Interior
  { slug: "ford", name: "Ford", category: "interior" },
  { slug: "honda", name: "Honda", category: "interior" },
  { slug: "nissan", name: "Nissan", category: "interior" },
  { slug: "subaru", name: "Subaru", category: "interior" },
  { slug: "toyota", name: "Toyota", category: "interior" },
  { slug: "volkswagen", name: "Volkswagen", category: "interior" },

  // 4x4 Accessories
  { slug: "arb", name: "ARB", category: "4x4-accessories" },
  { slug: "safari", name: "Safari", category: "4x4-accessories" },
  { slug: "tjm", name: "TJM", category: "4x4-accessories" },
  { slug: "ironman-4x4", name: "Ironman 4x4", category: "4x4-accessories" },
  { slug: "ecb", name: "ECB", category: "4x4-accessories" },
  { slug: "afn", name: "AFN", category: "4x4-accessories" },
  { slug: "rhino-rack", name: "Rhino-Rack", category: "4x4-accessories" },
  { slug: "yakima", name: "Yakima", category: "4x4-accessories" },
  { slug: "front-runner", name: "Front Runner", category: "4x4-accessories" },
  { slug: "rola", name: "Rola", category: "4x4-accessories" },
  { slug: "volkswagen", name: "Volkswagen", category: "4x4-accessories" },

  // Aftermarket
  { slug: "ford", name: "Ford", category: "aftermarket" },
  { slug: "bilstein", name: "Bilstein", category: "aftermarket" },
  { slug: "leer", name: "Leer", category: "aftermarket" },
  { slug: "snugtop", name: "Snugtop", category: "aftermarket" },
  { slug: "universal", name: "Universal", category: "aftermarket" },
  { slug: "toyota", name: "Toyota", category: "aftermarket" },
  { slug: "honda", name: "Honda", category: "aftermarket" },
  { slug: "bmw", name: "BMW", category: "aftermarket" },
  { slug: "behr", name: "Behr", category: "aftermarket" },
  { slug: "mercedes-benz", name: "Mercedes-Benz", category: "aftermarket" },
  { slug: "audi", name: "Audi", category: "aftermarket" },
  { slug: "chevrolet", name: "Chevrolet", category: "aftermarket" },
  { slug: "nissan", name: "Nissan", category: "aftermarket" },
  { slug: "jaguar", name: "Jaguar", category: "aftermarket" },
  { slug: "lexus", name: "Lexus", category: "aftermarket" },
  { slug: "jeep", name: "Jeep", category: "aftermarket" },

  // Wheels & Tires
  { slug: "bfgoodrich", name: "BFGoodrich", category: "wheels-tires" },
  { slug: "falken", name: "Falken", category: "wheels-tires" },
  { slug: "michelin", name: "Michelin", category: "wheels-tires" },
  { slug: "pirelli", name: "Pirelli", category: "wheels-tires" },
  { slug: "nitto", name: "Nitto", category: "wheels-tires" },
  { slug: "cooper", name: "Cooper Tires", category: "wheels-tires" },
  { slug: "yokohama", name: "Yokohama", category: "wheels-tires" },
  { slug: "bimmerworld", name: "BimmerWorld", category: "wheels-tires" },
  { slug: "apex", name: "APEX", category: "wheels-tires" },
  { slug: "sonax", name: "SONAX", category: "wheels-tires" },
  { slug: "toyo", name: "Toyo", category: "wheels-tires" },
  { slug: "bmw", name: "BMW", category: "wheels-tires" },
  { slug: "hr", name: "H&R", category: "wheels-tires" },
  { slug: "turner-motorsport", name: "Turner Motorsport", category: "wheels-tires" },
  { slug: "motorsport-hardware", name: "Motorsport Hardware", category: "wheels-tires" },
  { slug: "volk-racing", name: "Volk Racing", category: "wheels-tires" },
  { slug: "method-race-wheels", name: "Method Race Wheels", category: "wheels-tires" },
  { slug: "fuel-off-road", name: "Fuel Off-Road", category: "wheels-tires" },
  { slug: "universal", name: "Universal", category: "wheels-tires" },
];
