/* =========================================================
   DRIVORAPARTS — BRANDS (SINGLE SOURCE OF TRUTH)
   ---------------------------------------------------------
   Brands are grouped by category slug. Each brand `slug` is
   the kebab-case form of its `name` so it resolves cleanly
   in /catalog/[category]/[brand] routes.
========================================================= */

import type { Brand } from "./types";

export const brands: Brand[] = [
  // Engine
  { slug: "bmw", name: "BMW", category: "engine" },
  { slug: "toyota", name: "Toyota", category: "engine" },
  { slug: "nissan", name: "Nissan", category: "engine" },
  { slug: "honda", name: "Honda", category: "engine" },
  { slug: "mazda", name: "Mazda", category: "engine" },
  { slug: "chevrolet", name: "Chevrolet", category: "engine" },
  { slug: "ford", name: "Ford", category: "engine" },
  { slug: "dodge", name: "Dodge", category: "engine" },
  { slug: "aeromotive", name: "Aeromotive", category: "engine" },
  { slug: "holley", name: "Holley", category: "engine" },
  { slug: "garrett", name: "Garrett", category: "engine" },
  { slug: "borgwarner", name: "BorgWarner", category: "engine" },
  { slug: "precision", name: "Precision", category: "engine" },
  { slug: "hks", name: "HKS", category: "engine" },
  { slug: "turbosmart", name: "Turbosmart", category: "engine" },
  { slug: "forge-motorsport", name: "Forge Motorsport", category: "engine" },
  { slug: "universal", name: "Universal", category: "engine" },
  { slug: "turn-one", name: "Turn One", category: "engine" },
  { slug: "borgeson", name: "Borgeson Universal", category: "engine" },
  { slug: "unisteer", name: "UniSteer Performance", category: "engine" },
  { slug: "psc-motorsports", name: "PSC Motorsports", category: "engine" },
  { slug: "tuff-stuff", name: "Tuff Stuff Performance", category: "engine" },
  { slug: "acdelco", name: "ACDelco", category: "engine" },
  { slug: "motorcraft", name: "Motorcraft", category: "engine" },
  { slug: "delphi", name: "Delphi Technologies", category: "engine" },

  // Diesel specialists supplying the OBS 7.3 Power Stroke cluster.
  { slug: "freedom-injection", name: "Freedom Injection", category: "engine" },
  { slug: "dieselsite", name: "DieselSite", category: "engine" },
  { slug: "driven-diesel", name: "Driven Diesel", category: "engine" },
  { slug: "alliant-power", name: "Alliant Power", category: "engine" },
  { slug: "alliant-power", name: "Alliant Power", category: "electronics" },
  { slug: "mishimoto", name: "Mishimoto", category: "engine" },
  // Market expansion (2026-09): brands added for the USA and Australia listings.
  { slug: "s-and-b", name: "S&B Filters", category: "engine" },
  { slug: "jlt", name: "JLT Performance", category: "engine" },
  { slug: "bd-diesel", name: "BD Diesel", category: "engine" },
  { slug: "bosch", name: "Bosch", category: "engine" },
  { slug: "industrial-injection", name: "Industrial Injection", category: "engine" },
  { slug: "fleece", name: "Fleece Performance", category: "engine" },
  { slug: "fass", name: "FASS Fuel Systems", category: "engine" },
  { slug: "s-and-s-diesel", name: "S&S Diesel Motorsport", category: "engine" },
  { slug: "purepower", name: "PurePower Technologies", category: "engine" },
  { slug: "airdog", name: "AirDog", category: "engine" },
  { slug: "cummins", name: "Cummins", category: "engine" },
  { slug: "dynomite-diesel", name: "Dynomite Diesel", category: "engine" },
  { slug: "power-driven-diesel", name: "Power Driven Diesel", category: "engine" },
  { slug: "no-limit-fabrication", name: "No Limit Fabrication", category: "engine" },
  { slug: "grizzly", name: "Grizzly", category: "engine" },
  { slug: "smeding-diesel", name: "Smeding Diesel", category: "engine" },
  { slug: "ford", name: "Ford", category: "engine" },
  { slug: "bulletproof-diesel", name: "BulletProof Diesel", category: "engine" },
  { slug: "sinister-diesel", name: "Sinister Diesel", category: "engine" },
  { slug: "dieselsite", name: "DieselSite", category: "engine" },
  { slug: "driven-diesel", name: "Driven Diesel", category: "engine" },
  { slug: "csf", name: "CSF Radiators", category: "engine" },
  { slug: "ppe", name: "PPE Diesel", category: "engine" },
  { slug: "afe", name: "aFe Power", category: "engine" },
  { slug: "banks-power", name: "Banks Power", category: "engine" },
  { slug: "kc-turbos", name: "KC Turbos", category: "engine" },
  { slug: "xdp", name: "XDP", category: "engine" },

  // Turbocharger
  { slug: "garrett", name: "Garrett", category: "turbocharger" },
  // Needed for the OBS 7.3 Power Stroke TP38, which is a Ford part number.
  { slug: "ford", name: "Ford", category: "turbocharger" },
  { slug: "borgwarner", name: "BorgWarner", category: "turbocharger" },
  { slug: "precision", name: "Precision", category: "turbocharger" },
  { slug: "audi", name: "Audi", category: "turbocharger" },
  { slug: "bmw", name: "BMW", category: "turbocharger" },
  { slug: "universal", name: "Universal", category: "turbocharger" },
  // Market expansion (2026-09): brands added for the USA and Australia listings.
  { slug: "bd-diesel", name: "BD Diesel", category: "turbocharger" },
  { slug: "holset", name: "Holset", category: "turbocharger" },
  { slug: "industrial-injection", name: "Industrial Injection", category: "turbocharger" },
  { slug: "fleece", name: "Fleece Performance", category: "turbocharger" },
  { slug: "kc-turbos", name: "KC Turbos", category: "turbocharger" },
  { slug: "alliant-power", name: "Alliant Power", category: "turbocharger" },
  { slug: "synapse-auto", name: "Synapse Auto", category: "turbocharger" },
  { slug: "river-city-turbo", name: "River City Turbo", category: "turbocharger" },
  { slug: "power-driven-diesel", name: "Power Driven Diesel", category: "turbocharger" },
  { slug: "ats", name: "ATS Diesel Performance", category: "turbocharger" },
  { slug: "afe", name: "aFe Power", category: "turbocharger" },
  { slug: "rotomaster", name: "Rotomaster", category: "turbocharger" },

  // Transmission
  { slug: "zf", name: "ZF", category: "transmission" },
  { slug: "gm", name: "GM", category: "transmission" },
  { slug: "ford", name: "Ford", category: "transmission" },
  { slug: "tremec", name: "Tremec", category: "transmission" },
  { slug: "nissan", name: "Nissan", category: "transmission" },
  { slug: "toyota", name: "Toyota", category: "transmission" },
  { slug: "mercedes-benz", name: "Mercedes-Benz", category: "transmission" },
  { slug: "audi", name: "Audi", category: "transmission" },
  { slug: "bmw", name: "BMW", category: "transmission" },
  { slug: "universal", name: "Universal", category: "transmission" },
  { slug: "getrag", name: "Getrag", category: "transmission" },
  { slug: "aisin", name: "Aisin", category: "transmission" },
  { slug: "allison", name: "Allison", category: "transmission" },
  { slug: "nismo", name: "Nismo", category: "transmission" },
  { slug: "ford-performance", name: "Ford Performance", category: "transmission" },
  { slug: "chevrolet-performance", name: "Chevrolet Performance", category: "transmission" },
  { slug: "atsg", name: "ATSG", category: "transmission" },
  { slug: "sonnax", name: "Sonnax", category: "transmission" },
  { slug: "transgo", name: "TransGo", category: "transmission" },
  { slug: "xtreme-clutch", name: "Xtreme Clutch", category: "transmission" },
  { slug: "exedy", name: "Exedy", category: "transmission" },
  { slug: "act", name: "ACT", category: "transmission" },
  { slug: "south-bend", name: "South Bend Clutch", category: "transmission" },
  { slug: "centerforce", name: "Centerforce", category: "transmission" },

  { slug: "zumbrota", name: "Zumbrota Drivetrain", category: "transmission" },
  { slug: "bd-diesel", name: "BD Diesel", category: "transmission" },
  { slug: "mag-hytec", name: "Mag-Hytec", category: "transmission" },
  { slug: "suncoast", name: "SunCoast Performance", category: "transmission" },
  { slug: "ppe", name: "PPE Diesel", category: "transmission" },
  { slug: "ats", name: "ATS Diesel Performance", category: "transmission" },
  { slug: "afe", name: "aFe Power", category: "transmission" },
  { slug: "valair", name: "Valair Clutch", category: "transmission" },
  { slug: "south-bend-clutch", name: "South Bend Clutch", category: "transmission" },
  { slug: "merchant-automotive", name: "Merchant Automotive", category: "transmission" },
  { slug: "cognito", name: "Cognito Motorsports", category: "transmission" },

  // Bumpers
  { slug: "arb", name: "ARB", category: "bumper" },
  { slug: "tjm", name: "TJM", category: "bumper" },
  { slug: "ironman-4x4", name: "Ironman 4x4", category: "bumper" },
  { slug: "ecb", name: "ECB", category: "bumper" },
  { slug: "afn", name: "AFN", category: "bumper" },
  { slug: "add-offroad", name: "ADD Offroad", category: "bumper" },
  { slug: "dv8-offroad", name: "DV8 Offroad", category: "bumper" },
  { slug: "fab-fours", name: "Fab Fours", category: "bumper" },
  { slug: "rough-country", name: "Rough Country", category: "bumper" },
  { slug: "duraflex", name: "Duraflex", category: "bumper" },
  { slug: "liberty-walk", name: "Liberty Walk", category: "bumper" },
  { slug: "rocket-bunny", name: "Rocket Bunny", category: "bumper" },
  { slug: "ford", name: "Ford", category: "bumper" },
  { slug: "nissan", name: "Nissan", category: "bumper" },
  { slug: "roo-riders", name: "Roo Riders", category: "bumper" },
  // Market expansion (2026-09): brands added for the USA and Australia listings.
  { slug: "dobinsons", name: "Dobinsons", category: "bumper" },
  { slug: "westin", name: "Westin", category: "bumper" },

  // Canopies
  { slug: "arb", name: "ARB", category: "canopy" },
  { slug: "rsi-smartcap", name: "RSI SmartCap", category: "canopy" },
  { slug: "alu-cab", name: "Alu-Cab", category: "canopy" },
  { slug: "aeroklas", name: "Aeroklas", category: "canopy" },
  { slug: "egr", name: "EGR", category: "canopy" },
  { slug: "carryboy", name: "Carryboy", category: "canopy" },
  { slug: "flexiglass", name: "Flexiglass", category: "canopy" },
  { slug: "norweld", name: "Norweld", category: "canopy" },
  { slug: "boss-aluminium", name: "Boss Aluminium", category: "canopy" },
  { slug: "mrt", name: "MRT", category: "canopy" },
  { slug: "hsp", name: "HSP", category: "canopy" },
  { slug: "razorback", name: "Razorback", category: "canopy" },
  { slug: "tjm", name: "TJM", category: "canopy" },
  { slug: "mountain-top", name: "Mountain Top", category: "canopy" },
  { slug: "truck-covers-usa", name: "Truck Covers USA", category: "canopy" },
  { slug: "leer", name: "Leer", category: "canopy" },
  { slug: "snugtop", name: "SnugTop", category: "canopy" },
  { slug: "are-covers", name: "A.R.E.", category: "canopy" },
  { slug: "century", name: "Century", category: "canopy" },
  { slug: "jason", name: "Jason", category: "canopy" },
  { slug: "ranch", name: "Ranch", category: "canopy" },
  { slug: "front-runner", name: "Front Runner", category: "canopy" },

  // Brakes
  { slug: "brembo-gt-kits", name: "Brembo GT Kits", category: "brakes" },
  { slug: "bosch", name: "Bosch", category: "brakes" },
  { slug: "ssbc", name: "SSBC-USA", category: "brakes" },
  { slug: "hawk", name: "Hawk Performance", category: "brakes" },
  { slug: "mevotech", name: "Mevotech", category: "brakes" },
  { slug: "carli", name: "Carli Suspension", category: "brakes" },
  { slug: "icon-vehicle-dynamics", name: "ICON Vehicle Dynamics", category: "brakes" },
  { slug: "brembo-oem", name: "Brembo OEM", category: "brakes" },
  { slug: "wilwood-big-brake-kits", name: "Wilwood Big Brake Kits", category: "brakes" },
  { slug: "ebc-rotors-pads", name: "EBC Rotors & Pads", category: "brakes" },
  { slug: "ate-oem-kits", name: "ATE OEM Kits", category: "brakes" },
  { slug: "ceika", name: "CEIKA", category: "brakes" },

  // Suspension
  { slug: "old-man-emu", name: "Old Man Emu (OME / ARB)", category: "suspension" },
  { slug: "dobinsons", name: "Dobinsons", category: "suspension" },
  { slug: "bilstein", name: "Bilstein", category: "suspension" },
  { slug: "fox-racing-shox", name: "Fox Racing Shox", category: "suspension" },
  { slug: "king-shocks", name: "King Shocks", category: "suspension" },
  { slug: "ironman-4x4", name: "Ironman 4x4", category: "suspension" },
  { slug: "tough-dog", name: "Tough Dog", category: "suspension" },
  // Market expansion (2026-09): brands added for the USA and Australia listings.
  { slug: "air-lift", name: "Air Lift", category: "suspension" },
  { slug: "icon-vehicle-dynamics", name: "ICON Vehicle Dynamics", category: "suspension" },
  { slug: "emf", name: "EMF Ball Joints", category: "suspension" },
  { slug: "dynatrac", name: "Dynatrac", category: "suspension" },
  { slug: "mevotech", name: "Mevotech", category: "suspension" },
  { slug: "moog", name: "MOOG", category: "suspension" },
  { slug: "kryptonite", name: "Kryptonite Products", category: "suspension" },
  { slug: "axiom-supply", name: "Axiom Supply", category: "suspension" },
  { slug: "spyntec", name: "Spyntec Industries", category: "suspension" },
  { slug: "yukon-gear", name: "Yukon Gear & Axle", category: "suspension" },
  { slug: "warn", name: "WARN", category: "suspension" },
  { slug: "pmf-suspension", name: "PMF Suspension", category: "suspension" },
  { slug: "zone-offroad", name: "Zone Offroad", category: "suspension" },
  { slug: "bds-suspension", name: "BDS Suspension", category: "suspension" },
  { slug: "readylift", name: "ReadyLIFT", category: "suspension" },
  { slug: "mopar", name: "Mopar", category: "suspension" },
  { slug: "afe", name: "aFe Power", category: "suspension" },
  { slug: "bd-diesel", name: "BD Diesel", category: "suspension" },
  { slug: "eibach", name: "Eibach", category: "suspension" },
  { slug: "camburg", name: "Camburg Engineering", category: "suspension" },
  { slug: "fabtech", name: "Fabtech", category: "suspension" },
  { slug: "apex-chassis", name: "Apex Chassis", category: "suspension" },
  { slug: "synergy", name: "Synergy Manufacturing", category: "suspension" },
  { slug: "red-head-steering-gears", name: "Red-Head Steering Gears", category: "suspension" },
  { slug: "s-and-b", name: "S&B Filters", category: "suspension" },
  { slug: "rare-parts", name: "Rare Parts", category: "suspension" },
  { slug: "xdp", name: "XDP", category: "suspension" },

  // Electronics
  // OBS 7.3 Power Stroke sensors carry Ford / Motorcraft part numbers.
  { slug: "ford", name: "Ford", category: "electronics" },
  { slug: "aem", name: "AEM", category: "electronics" },
  { slug: "aeromotive", name: "Aeromotive", category: "electronics" },
  { slug: "holley", name: "Holley", category: "electronics" },
  { slug: "cobb", name: "COBB Tuning", category: "electronics" },
  { slug: "haltech", name: "Haltech", category: "electronics" },
  { slug: "hp-tuners", name: "HP Tuners", category: "electronics" },
  { slug: "msd", name: "MSD", category: "electronics" },
  { slug: "carlinkit", name: "CarlinKit", category: "electronics" },
  { slug: "ottocast", name: "Ottocast", category: "electronics" },
  { slug: "volkswagen", name: "Volkswagen", category: "electronics" },
  { slug: "universal", name: "Universal", category: "electronics" },
  { slug: "bosch", name: "Bosch", category: "electronics" },
  { slug: "fleece", name: "Fleece Performance", category: "electronics" },
  { slug: "mechman", name: "Mechman Alternators", category: "electronics" },
  { slug: "driven-diesel", name: "Driven Diesel", category: "electronics" },
  { slug: "mean-green", name: "Mean Green", category: "electronics" },
  { slug: "powermaster", name: "Powermaster Performance", category: "electronics" },
  { slug: "xdp", name: "XDP", category: "electronics" },

  // Lighting
  { slug: "alpharex", name: "AlphaRex", category: "lighting" },
  { slug: "sick-diesel", name: "Sick Diesel", category: "lighting" },
  { slug: "baja-designs", name: "Baja Designs", category: "lighting" },
  { slug: "diode-dynamics", name: "Diode Dynamics", category: "lighting" },
  { slug: "govee", name: "Govee", category: "lighting" },
  { slug: "morimoto", name: "Morimoto", category: "lighting" },
  { slug: "opt7", name: "OPT7", category: "lighting" },
  { slug: "oracle", name: "Oracle Lighting", category: "lighting" },
  { slug: "osram", name: "Osram", category: "lighting" },
  { slug: "philips", name: "Philips", category: "lighting" },
  { slug: "rigid-industries", name: "Rigid Industries", category: "lighting" },
  { slug: "xk-glow", name: "XK Glow", category: "lighting" },
  { slug: "anzo", name: "Anzo USA", category: "lighting" },
  { slug: "spyder", name: "Spyder Auto", category: "lighting" },
  { slug: "vland", name: "VLAND", category: "lighting" },
  { slug: "toyota", name: "Toyota Genuine", category: "lighting" },
  { slug: "ford", name: "Ford Genuine", category: "lighting" },
  { slug: "nissan", name: "Nissan Genuine", category: "lighting" },
  { slug: "isuzu", name: "Isuzu Genuine", category: "lighting" },
  { slug: "porsche", name: "Porsche", category: "lighting" },
  { slug: "mars-performance", name: "Mars Performance", category: "lighting" },
  { slug: "universal", name: "Universal", category: "lighting" },
  // Market expansion (2026-09): brands added for the USA and Australia listings.
  { slug: "arb", name: "ARB", category: "lighting" },
  { slug: "nacho", name: "NACHO", category: "lighting" },

  // Body Parts
  { slug: "bmw", name: "BMW", category: "body-parts" },
  { slug: "t-rex-grilles", name: "T-Rex Grilles", category: "body-parts" },
  { slug: "royalty-core", name: "Royalty Core", category: "body-parts" },
  { slug: "chevrolet", name: "Chevrolet", category: "body-parts" },
  { slug: "dodge", name: "Dodge", category: "body-parts" },
  { slug: "ford", name: "Ford", category: "body-parts" },
  { slug: "gmc", name: "GMC", category: "body-parts" },
  { slug: "honda", name: "Honda", category: "body-parts" },
  { slug: "nissan", name: "Nissan", category: "body-parts" },
  { slug: "subaru", name: "Subaru", category: "body-parts" },
  { slug: "toyota", name: "Toyota", category: "body-parts" },
  { slug: "volkswagen", name: "Volkswagen", category: "body-parts" },
  { slug: "universal", name: "Universal", category: "body-parts" },

  // Interior
  { slug: "ford", name: "Ford", category: "interior" },
  { slug: "honda", name: "Honda", category: "interior" },
  { slug: "nissan", name: "Nissan", category: "interior" },
  { slug: "subaru", name: "Subaru", category: "interior" },
  { slug: "toyota", name: "Toyota", category: "interior" },
  { slug: "volkswagen", name: "Volkswagen", category: "interior" },

  // 4x4 Accessories
  { slug: "arb", name: "ARB", category: "4x4-accessories" },
  { slug: "safari", name: "Safari", category: "4x4-accessories" },
  { slug: "tjm", name: "TJM", category: "4x4-accessories" },
  { slug: "ironman-4x4", name: "Ironman 4x4", category: "4x4-accessories" },
  { slug: "ecb", name: "ECB", category: "4x4-accessories" },
  { slug: "afn", name: "AFN", category: "4x4-accessories" },
  { slug: "rhino-rack", name: "Rhino-Rack", category: "4x4-accessories" },
  { slug: "yakima", name: "Yakima", category: "4x4-accessories" },
  { slug: "front-runner", name: "Front Runner", category: "4x4-accessories" },
  { slug: "rola", name: "Rola", category: "4x4-accessories" },
  { slug: "volkswagen", name: "Volkswagen", category: "4x4-accessories" },
  // Market expansion (2026-09): brands added for the USA and Australia listings.
  { slug: "warn", name: "WARN", category: "4x4-accessories" },
  { slug: "maxtrax", name: "MAXTRAX", category: "4x4-accessories" },
  { slug: "dobinsons", name: "Dobinsons", category: "4x4-accessories" },
  { slug: "aev", name: "AEV (American Expedition Vehicles)", category: "4x4-accessories" },
  { slug: "s-and-b", name: "S&B Filters", category: "4x4-accessories" },

  // Aftermarket
  { slug: "ford", name: "Ford", category: "aftermarket" },
  { slug: "bilstein", name: "Bilstein", category: "aftermarket" },
  { slug: "leer", name: "Leer", category: "aftermarket" },
  { slug: "snugtop", name: "Snugtop", category: "aftermarket" },
  { slug: "universal", name: "Universal", category: "aftermarket" },
  { slug: "toyota", name: "Toyota", category: "aftermarket" },
  { slug: "honda", name: "Honda", category: "aftermarket" },
  { slug: "bmw", name: "BMW", category: "aftermarket" },
  { slug: "behr", name: "Behr", category: "aftermarket" },
  { slug: "mercedes-benz", name: "Mercedes-Benz", category: "aftermarket" },
  { slug: "audi", name: "Audi", category: "aftermarket" },
  { slug: "chevrolet", name: "Chevrolet", category: "aftermarket" },
  { slug: "nissan", name: "Nissan", category: "aftermarket" },
  { slug: "jaguar", name: "Jaguar", category: "aftermarket" },
  { slug: "lexus", name: "Lexus", category: "aftermarket" },
  { slug: "jeep", name: "Jeep", category: "aftermarket" },
  { slug: "chrysler", name: "Chrysler", category: "aftermarket" },
  { slug: "hino", name: "Hino", category: "aftermarket" },
  { slug: "cardone", name: "Cardone Industries", category: "aftermarket" },

  // Wheels & Tires
  { slug: "bfgoodrich", name: "BFGoodrich", category: "wheels-tires" },
  { slug: "falken", name: "Falken", category: "wheels-tires" },
  { slug: "michelin", name: "Michelin", category: "wheels-tires" },
  { slug: "pirelli", name: "Pirelli", category: "wheels-tires" },
  { slug: "nitto", name: "Nitto", category: "wheels-tires" },
  { slug: "cooper", name: "Cooper Tires", category: "wheels-tires" },
  { slug: "yokohama", name: "Yokohama", category: "wheels-tires" },
  { slug: "bimmerworld", name: "BimmerWorld", category: "wheels-tires" },
  { slug: "apex", name: "APEX", category: "wheels-tires" },
  { slug: "sonax", name: "SONAX", category: "wheels-tires" },
  { slug: "toyo", name: "Toyo", category: "wheels-tires" },
  { slug: "bmw", name: "BMW", category: "wheels-tires" },
  { slug: "hr", name: "H&R", category: "wheels-tires" },
  { slug: "turner-motorsport", name: "Turner Motorsport", category: "wheels-tires" },
  { slug: "motorsport-hardware", name: "Motorsport Hardware", category: "wheels-tires" },
  { slug: "volk-racing", name: "Volk Racing", category: "wheels-tires" },
  { slug: "method-race-wheels", name: "Method Race Wheels", category: "wheels-tires" },
  { slug: "fuel-off-road", name: "Fuel Off-Road", category: "wheels-tires" },
  { slug: "universal", name: "Universal", category: "wheels-tires" },
];
