import photography from "@/lib/content/homepage-photography.json";

/**
 * Homepage photography, read from the acquisition manifest.
 *
 * The manifest is the single source of truth for every editorial image: which
 * file to render, its intrinsic size, and where it came from. Page code never
 * hard-codes an image path, so re-running the acquisition script against a
 * better source swaps the photography without touching a component.
 *
 * `images: { unoptimized: true }` is set for the Cloudflare adapter, so Next
 * does no resizing at runtime. Every width here is pre-generated by the
 * acquisition script, and callers must render explicit width/height so the
 * browser reserves the box before the bytes land.
 */

export type PhotoVariant = { width: number; file: string; bytes: number };

export type Photo = {
  slot: string;
  status: string;
  purpose?: string;
  vehicle?: string | null;
  sourceName?: string;
  sourceUrl?: string;
  landingPage?: string;
  title?: string;
  creator?: string | null;
  license?: string;
  licenseRaw?: string;
  licenseUrl?: string;
  attributionRequired?: boolean;
  intrinsicWidth?: number;
  intrinsicHeight?: number;
  variants?: PhotoVariant[];
};

const PHOTOS = photography as Record<string, Photo>;

/** A slot that never resolved is not an error -- the section renders without art. */
export function getPhoto(slot: string): Photo | null {
  const p = PHOTOS[slot];
  return p && p.status === "ok" && p.variants && p.variants.length ? p : null;
}

export type HeroVideoAsset = {
  file: string;
  poster: string;
  bytes: number;
  durationSeconds: number;
};

/**
 * The hero clip, which is not a Photo: it has a single file and a poster
 * rather than a responsive `variants` array, so getPhoto() rejects it. Asking
 * getPhoto for it silently returned null and the hero fell back to the still.
 */
export function getHeroVideo(): HeroVideoAsset | null {
  const v = PHOTOS["hero-video"] as Photo & Partial<HeroVideoAsset>;
  if (!v || v.status !== "ok" || !v.file || !v.poster) return null;
  return {
    file: v.file,
    poster: v.poster,
    bytes: v.bytes ?? 0,
    durationSeconds: v.durationSeconds ?? 0,
  };
}

export type PhotoRender = {
  src: string;
  srcSet: string;
  width: number;
  height: number;
  credit: string | null;
  creditHref: string | null;
};

/**
 * Everything a component needs to render one photograph correctly.
 * `src` is the largest variant, so a browser that ignores srcSet still gets a
 * usable image rather than the 640px thumbnail.
 */
export function renderPhoto(slot: string): PhotoRender | null {
  const p = getPhoto(slot);
  if (!p || !p.variants?.length) return null;
  const variants = [...p.variants].sort((a, b) => a.width - b.width);
  const largest = variants[variants.length - 1];
  const ratio = p.intrinsicHeight && p.intrinsicWidth ? p.intrinsicHeight / p.intrinsicWidth : 9 / 16;

  return {
    src: largest.file,
    srcSet: variants.map((v) => `${v.file} ${v.width}w`).join(", "),
    width: largest.width,
    height: Math.round(largest.width * ratio),
    // Only surface a credit where the licence actually demands one. CC0, public
    // domain and the Pexels Licence do not, and printing a name anyway would
    // imply a requirement that does not exist.
    credit: p.attributionRequired ? `${p.creator || "Unknown"} · ${p.licenseRaw || p.license}` : null,
    creditHref: p.attributionRequired ? p.landingPage || null : null,
  };
}

/** Every image whose licence requires a credit line, for the colophon. */
export function attributions(): Photo[] {
  return Object.values(PHOTOS)
    .filter((p) => p.status === "ok" && p.attributionRequired)
    .sort((a, b) => (a.slot || "").localeCompare(b.slot || ""));
}
