import photography from "@/lib/content/homepage-photography.json";

/**
 * Homepage photography, read from the acquisition manifest.
 *
 * The manifest is the single source of truth for every editorial image: which
 * file to render, its intrinsic size, and where it came from. Page code never
 * hard-codes an image path, so re-running the acquisition script against a
 * better source swaps the photography without touching a component.
 *
 * `images: { unoptimized: true }` is set for the Cloudflare adapter, so Next
 * does no resizing at runtime. Every width here is pre-generated by the
 * acquisition script, and callers must render explicit width/height so the
 * browser reserves the box before the bytes land.
 */

export type PhotoVariant = { width: number; file: string; bytes: number };

export type Photo = {
  slot: string;
  status: string;
  purpose?: string;
  vehicle?: string | null;
  sourceName?: string;
  sourceUrl?: string;
  landingPage?: string;
  title?: string;
  creator?: string | null;
  license?: string;
  licenseRaw?: string;
  licenseUrl?: string;
  attributionRequired?: boolean;
  intrinsicWidth?: number;
  intrinsicHeight?: number;
  variants?: PhotoVariant[];
  /* Optional parallel AVIF renditions. Only generated where WebP is
     expensive -- dense, high-frequency subjects such as bare branches, where
     AVIF is worth the extra encode. */
  avifVariants?: PhotoVariant[];
};

const PHOTOS = photography as Record<string, Photo>;

/** A slot that never resolved is not an error -- the section renders without art. */
export function getPhoto(slot: string): Photo | null {
  const p = PHOTOS[slot];
  return p && p.status === "ok" && p.variants && p.variants.length ? p : null;
}

export type HeroSegment = { start: number; end: number; label: string };

export type HeroVideoAsset = {
  file: string;
  poster: string;
  /** Responsive stills, used on phones where the clip is not downloaded. */
  posterSrcSet: string | null;
  bytes: number;
  durationSeconds: number;
  /**
   * Where each shot sits inside the montage, in seconds.
   *
   * hero.mp4 is a hard-cut concatenation -- no crossfades -- so these
   * boundaries are exact frames rather than approximations, which is what lets
   * the player seek between shots without landing mid-dissolve. Empty when the
   * manifest records no shot list, and the player then leaves playback alone.
   */
  segments: HeroSegment[];
};

/**
 * The hero clip, which is not a Photo: it has a single file and a poster
 * rather than a responsive `variants` array, so getPhoto() rejects it. Asking
 * getPhoto for it silently returned null and the hero fell back to the still.
 */
export function getHeroVideo(): HeroVideoAsset | null {
  const v = PHOTOS["hero-video"] as Photo & Partial<HeroVideoAsset>;
  if (!v || v.status !== "ok" || !v.file || !v.poster) return null;
  const posters = (v as { posterVariants?: PhotoVariant[] }).posterVariants;

  // Cumulative, because the manifest records each shot as a duration rather
  // than an offset. A shot with a missing or nonsensical length is dropped
  // instead of poisoning every offset that follows it.
  const shots = (v as { shots?: { label?: string; seconds?: number }[] }).shots ?? [];
  let at = 0;
  const segments: HeroSegment[] = [];
  for (const shot of shots) {
    const seconds = Number(shot?.seconds);
    if (!Number.isFinite(seconds) || seconds <= 0) continue;
    segments.push({ start: at, end: at + seconds, label: shot?.label ?? "" });
    at += seconds;
  }

  return {
    file: v.file,
    poster: v.poster,
    posterSrcSet: posters?.length
      ? [...posters].sort((a, b) => a.width - b.width).map((x) => `${x.file} ${x.width}w`).join(", ")
      : null,
    bytes: v.bytes ?? 0,
    durationSeconds: v.durationSeconds ?? 0,
    segments,
  };
}

export type PhotoRender = {
  src: string;
  srcSet: string;
  /** Null unless AVIF renditions were generated for this slot. */
  avifSrcSet: string | null;
  width: number;
  height: number;
  credit: string | null;
  creditHref: string | null;
};

/**
 * Everything a component needs to render one photograph correctly.
 * `src` is the largest variant, so a browser that ignores srcSet still gets a
 * usable image rather than the 640px thumbnail.
 */
export function renderPhoto(slot: string): PhotoRender | null {
  const p = getPhoto(slot);
  if (!p || !p.variants?.length) return null;
  const variants = [...p.variants].sort((a, b) => a.width - b.width);
  const largest = variants[variants.length - 1];
  const ratio = p.intrinsicHeight && p.intrinsicWidth ? p.intrinsicHeight / p.intrinsicWidth : 9 / 16;

  const avif = p.avifVariants?.length
    ? [...p.avifVariants].sort((a, b) => a.width - b.width)
    : null;

  return {
    src: largest.file,
    srcSet: variants.map((v) => `${v.file} ${v.width}w`).join(", "),
    avifSrcSet: avif ? avif.map((v) => `${v.file} ${v.width}w`).join(", ") : null,
    width: largest.width,
    height: Math.round(largest.width * ratio),
    // Only surface a credit where the licence actually demands one. CC0, public
    // domain and the Pexels Licence do not, and printing a name anyway would
    // imply a requirement that does not exist.
    credit: p.attributionRequired ? `${p.creator || "Unknown"} · ${p.licenseRaw || p.license}` : null,
    creditHref: p.attributionRequired ? p.landingPage || null : null,
  };
}

/** Every image whose licence requires a credit line, for the colophon. */
export function attributions(): Photo[] {
  return Object.values(PHOTOS)
    .filter((p) => p.status === "ok" && p.attributionRequired)
    .sort((a, b) => (a.slot || "").localeCompare(b.slot || ""));
}
