/** @type {Array<{name:string,brand:string,fitment:string,price:number,topDemand?:boolean,url?:string}>} */
export const CANOPY_SOURCES = [
  { name: "ARB Ascent Canopy", brand: "arb", fitment: "Toyota Hilux / Ford Ranger dual cab", price: 4699, topDemand: true, url: "https://www.arb.com.au/" },
  { name: "ARB Classic Canopy", brand: "arb", fitment: "Toyota Hilux dual cab", price: 3899, topDemand: true, url: "https://www.arb.com.au/" },
  { name: "ARB Commercial Canopy", brand: "arb", fitment: "Ford Ranger / Isuzu D-Max dual cab", price: 3599, topDemand: true, url: "https://www.arb.com.au/" },
  { name: "ARB Pinnacle Canopy", brand: "arb", fitment: "Toyota LandCruiser 300 dual cab", price: 5299, topDemand: true, url: "https://www.arb.com.au/" },
  { name: "RSI SmartCap EVO Adventure", brand: "rsi-smartcap", fitment: "Ford F-150 / RAM 1500", price: 4299, topDemand: true, url: "https://www.rsicap.com/" },
  { name: "RSI SmartCap EVO Sport", brand: "rsi-smartcap", fitment: "Toyota Tacoma / Chevrolet Colorado", price: 3999, topDemand: true, url: "https://www.rsicap.com/" },
  { name: "RSI SmartCap EVO Commercial", brand: "rsi-smartcap", fitment: "Ford F-250 / RAM 2500", price: 4499, topDemand: true, url: "https://www.rsicap.com/" },
  { name: "Alu-Cab Explorer Canopy", brand: "alu-cab", fitment: "Toyota Hilux / Ford Ranger", price: 5899, topDemand: true, url: "https://alucab.com/" },
  { name: "Alu-Cab Canopy Camper", brand: "alu-cab", fitment: "Toyota LandCruiser 79 / 300", price: 7499, topDemand: true, url: "https://alucab.com/" },
  { name: "Aeroklas Premium Canopy", brand: "aeroklas", fitment: "Ford Ranger / Toyota Hilux", price: 3299, topDemand: true, url: "https://www.aeroklas.com.au/" },
  { name: "Aeroklas Stylish Canopy", brand: "aeroklas", fitment: "Isuzu D-Max / Mitsubishi Triton", price: 2999, url: "https://www.aeroklas.com.au/" },
  { name: "Aeroklas Commercial Canopy", brand: "aeroklas", fitment: "Ford Ranger PX3 / Next Gen", price: 2799, url: "https://www.aeroklas.com.au/" },
  { name: "EGR Premium Canopy", brand: "egr", fitment: "Toyota Hilux N80 dual cab", price: 2899, url: "https://www.egrgroup.com.au/" },
  { name: "EGR Fleet Canopy", brand: "egr", fitment: "Ford Ranger dual cab", price: 2699, url: "https://www.egrgroup.com.au/" },
  { name: "EGR Commercial Canopy", brand: "egr", fitment: "Isuzu D-Max / Mazda BT-50", price: 2499, url: "https://www.egrgroup.com.au/" },
  { name: "Carryboy S560 Canopy", brand: "carryboy", fitment: "Toyota Hilux dual cab", price: 2799, url: "https://www.carryboy.com.au/" },
  { name: "Carryboy S6 Canopy", brand: "carryboy", fitment: "Ford Ranger dual cab", price: 2599, url: "https://www.carryboy.com.au/" },
  { name: "Carryboy Workman Canopy", brand: "carryboy", fitment: "Isuzu D-Max tradesman dual cab", price: 2399, url: "https://www.carryboy.com.au/" },
  { name: "Carryboy G3 Canopy", brand: "carryboy", fitment: "Mitsubishi Triton dual cab", price: 2499, url: "https://www.carryboy.com.au/" },
  { name: "Flexiglass Premium Canopy", brand: "flexiglass", fitment: "Toyota Hilux / Ford Ranger", price: 2699, url: "https://www.flexiglass.net.au/" },
  { name: "Flexiglass Tradesman Canopy", brand: "flexiglass", fitment: "Isuzu D-Max / Nissan Navara", price: 2299, url: "https://www.flexiglass.net.au/" },
  { name: "Flexiglass Sports Canopy", brand: "flexiglass", fitment: "Ford Ranger / Toyota Hilux", price: 2499, url: "https://www.flexiglass.net.au/" },
  { name: "Norweld Aluminium Canopy", brand: "norweld", fitment: "Toyota LandCruiser 79 dual cab", price: 4899, url: "https://norweld.com.au/" },
  { name: "Norweld Deluxe Canopy", brand: "norweld", fitment: "Ford Ranger / Toyota Hilux", price: 4599, url: "https://norweld.com.au/" },
  { name: "Boss Aluminium Canopy", brand: "boss-aluminium", fitment: "Toyota Hilux dual cab", price: 3799, url: "https://bossaluminium.com.au/" },
  { name: "Boss Premium Canopy", brand: "boss-aluminium", fitment: "Ford Ranger dual cab", price: 3999, url: "https://bossaluminium.com.au/" },
  { name: "MRT Aluminium Canopy", brand: "mrt", fitment: "Toyota Hilux / Ford Ranger", price: 3499, url: "https://www.mrt.com.au/" },
  { name: "HSP Premium Canopy", brand: "hsp", fitment: "Ford Ranger / Isuzu D-Max", price: 2199, url: "https://www.hsp.net.au/" },
  { name: "HSP Roll R Cover Canopy", brand: "hsp", fitment: "Toyota Hilux dual cab", price: 2399, url: "https://www.hsp.net.au/" },
  { name: "Razorback Aluminium Canopy", brand: "razorback", fitment: "Toyota LandCruiser 79 / Hilux", price: 4299, url: "https://razorbackcanopies.com.au/" },
  { name: "TJM Premium Canopy", brand: "tjm", fitment: "Toyota Hilux / Ford Ranger", price: 3199, url: "https://www.tjm.com.au/" },
  { name: "TJM Touring Canopy", brand: "tjm", fitment: "Toyota LandCruiser 300 / Prado", price: 3499, url: "https://www.tjm.com.au/" },
  { name: "Mountain Top Adventure Canopy", brand: "mountain-top", fitment: "Ford Ranger / Toyota Hilux", price: 3699, url: "https://www.mountaintop.com/" },
  { name: "Truck Covers USA Hard Canopy", brand: "truck-covers-usa", fitment: "Ford F-150 / Chevrolet Silverado 1500", price: 2199, url: "https://www.truckcoversusa.com/" },
  { name: "LEER 100XR Canopy", brand: "leer", fitment: "Full-size truck 6.5 ft bed", price: 2499, url: "https://www.leer.com/" },
  { name: "LEER 100XL Canopy", brand: "leer", fitment: "Full-size truck extended cab", price: 2699, url: "https://www.leer.com/" },
  { name: "LEER 180 Canopy", brand: "leer", fitment: "Mid-size truck 5 ft / 6 ft bed", price: 2299, url: "https://www.leer.com/" },
  { name: "SnugTop Rebel Canopy", brand: "snugtop", fitment: "Ford F-150 / RAM 1500", price: 2799, url: "https://www.snugtop.com/" },
  { name: "SnugTop Hi-Liner Canopy", brand: "snugtop", fitment: "Full-size truck cab-high applications", price: 2999, url: "https://www.snugtop.com/" },
  { name: "A.R.E. CX Classic Canopy", brand: "are-covers", fitment: "Ford F-150 / Chevrolet Silverado", price: 2199, url: "https://www.4are.com/" },
  { name: "A.R.E. MX Series Canopy", brand: "are-covers", fitment: "Mid-size truck 5 ft bed", price: 2399, url: "https://www.4are.com/" },
  { name: "A.R.E. Z2 Series Canopy", brand: "are-covers", fitment: "Ford F-150 / RAM 1500", price: 2599, url: "https://www.4are.com/" },
  { name: "Century Ultra Canopy", brand: "century", fitment: "Toyota Hilux / Ford Ranger (AU)", price: 2899, url: "https://www.century.com.au/" },
  { name: "Century High-C Sport Canopy", brand: "century", fitment: "Isuzu D-Max / Mitsubishi Triton", price: 2699, url: "https://www.century.com.au/" },
  { name: "Jason Trek Canopy", brand: "jason", fitment: "Toyota Hilux / Ford Ranger touring builds", price: 3199, url: "https://www.jasoncanopies.com.au/" },
  { name: "Jason Commercial Canopy", brand: "jason", fitment: "Isuzu D-Max / Nissan Navara fleet", price: 2799, url: "https://www.jasoncanopies.com.au/" },
  { name: "Ranch Icon Canopy", brand: "ranch", fitment: "Ford F-150 5.5 ft / 6.5 ft bed", price: 2099, url: "https://www.ranchcovers.com/" },
  { name: "Ranch Sierra Canopy", brand: "ranch", fitment: "Chevrolet Silverado / GMC Sierra", price: 2199, url: "https://www.ranchcovers.com/" },
  { name: "SmartCap EVO Defender Canopy", brand: "rsi-smartcap", fitment: "Toyota LandCruiser 70 / 300", price: 4799, url: "https://www.rsicap.com/" },
  { name: "Front Runner Canopy System", brand: "front-runner", fitment: "Toyota Hilux / Ford Ranger overland builds", price: 4199, url: "https://www.frontrunneroutfitters.com/" },
];
